version: "3.9"

services:
  postgres:
    image: postgres:13
    container_name: dotnet-posgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ~/.docker-static/dotnet-posgres/postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
  redis:
    image: redis:6.2.4
    container_name: dotnet-redis
    command: redis-server --appendonly yes
    volumes:
      - ~/.docker-static/dotnet-redis:/data
    ports:
      - "6379:6379"